# Generated by Django 4.2.1 on 2023-06-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
