# Generated by Django 4.2.1 on 2023-06-09 12:42

import accounts.phone_number
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=accounts.phone_number.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
    ]
