# Generated by Django 4.2.1 on 2023-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_homepagecarousel_sequence'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shoes',
            field=models.ManyToManyField(null=True, through='cart.CartItem', to='shoes.shoe'),
        ),
    ]
