# Generated by Django 4.2.1 on 2023-06-17 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
