# Generated by Django 4.2.1 on 2023-06-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='last_modified',
        ),
    ]
