# Generated by Django 4.2.1 on 2023-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoe_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_for_qty', models.IntegerField()),
                ('qty_for_size', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='qty',
        ),
        migrations.AddField(
            model_name='shoe',
            name='qty',
            field=models.ManyToManyField(to='shoes.qty'),
        ),
    ]
