# Generated by Django 4.2.1 on 2023-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_qty_size_for_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.DeleteModel(
            name='Qty',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='qty',
            field=models.ManyToManyField(to='shoes.qtysize'),
        ),
    ]
