# Generated by Django 4.2.1 on 2023-05-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_qtysize_remove_shoe_size_delete_qty_delete_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='shoe',
            name='type',
            field=models.CharField(choices=[('running', 'running'), ('retro', 'retro'), ('slip-on', 'slip-on'), ('low-top', 'low-top'), ('high-top', 'high-top'), ('skate', 'skate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.brand'),
        ),
    ]
