# Generated by Django 4.2.1 on 2023-05-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_brand_alter_shoe_type_alter_shoe_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='href',
        ),
    ]
