# Generated by Django 4.2.1 on 2023-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_homepagecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarousel',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
