# Generated by Django 4.2.1 on 2023-06-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_phone_number'),
        ('orders', '0002_order_created_at_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('canceled', 'canceled'), ('delivered', 'delivered'), ('processed', 'processed')], default='processed', max_length=55),
        ),
    ]
