# Generated by Django 4.2.1 on 2023-06-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_remove_shoe_qty_qtysize_shoe'),
        ('orders', '0003_order_address_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_size', models.IntegerField()),
                ('user_qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoe')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shoes',
            field=models.ManyToManyField(through='orders.OrderItem', to='shoes.shoe'),
        ),
    ]
